// src/store/index.js
import { createStore } from 'vuex';
import VuexPersistence from 'vuex-persist';

function loadSavedState() {
  const savedState = localStorage.getItem('vuexState');
  return savedState ? JSON.parse(savedState) : 
  {
    user: {
      email: null,
      uid: null,
      isAuthenticated: false,
      department: "CMPS",
    },
    layout:[],
    example: [
      { x: 2, y: 0, w: 2, h: 1, i: 'W', static: true },
      { x: 4, y: 0, w: 2, h: 1, i: 'E', static: true },
      { x: 6, y: 0, w: 2, h: 1, i: 'L', static: true },
      { x: 8, y: 0, w: 2, h: 1, i: 'C', static: true },
      { x: 10, y: 0, w: 2, h: 1, i: 'O', static: true },
      { x: 12, y: 0, w: 2, h: 1, i: 'M ', static: true },
      { x: 14, y: 0, w: 2, h: 1, i: 'E ', static: true },
      { x: 0, y: 1, w: 2, h: 1, i: 'M', static: true },
      { x: 0, y: 2, w: 2, h: 1, i: 'S', static: true },
      { x: 0, y: 3, w: 2, h: 1, i: 'U', static: true },
      { x: 0, y: 4, w: 2, h: 1, i: 'C ', static: true },
      { x: 0, y: 5, w: 2, h: 1, i: 'L ', static: true },
      { x: 0, y: 6, w: 2, h: 1, i: 'A', static: true },
      { x: 0, y: 7, w: 2, h: 1, i: 'S  ', static: true },
      { x: 0, y: 8, w: 2, h: 1, i: 'S ', static: true },
      { x: 0, y: 9, w: 2, h: 1, i: 'I', static: true },
      { x: 0, y: 10, w: 2, h: 1, i: 'C  ', static: true },
      { x: 2, y: 1, w: 2, h: 1, i: 'Class1', static: false },
    ],
    faculty_course: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 'Colmenares - Diaz', static: true, is_dept: true},
      {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 'Griffin', static: true, is_dept: true},
      {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 'Hood', static: true, is_dept: true},
      {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 'Johnson', static: true, is_dept: true},
      {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 'Morgan', static: true, is_dept: true},
      {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 'Passos', static: true, is_dept: true},
      {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 'Roychoudhuri', static: true, is_dept: true},
      {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 'Smith', static: true, is_dept: true},
      {'x': 9, 'y': 0, 'w': 1, 'h': 1, 'i': 'Stringfellow', static: true, is_dept: true},
      {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 'CMPS 1023', static: true, is_dept: true},
      {'x': 4, 'y': 1, 'w': 1, 'h': 1, 'i': 'TR 11:00 BO 103', static: true, is_dept: true},
      {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 'CMPS 1044', static: true, is_dept: true},
      {'x': 5, 'y': 2, 'w': 1, 'h': 1, 'i': 'MWF 9:00 BO 207', static: true, is_dept: true},
      {'x': 7, 'y': 2, 'w': 1, 'h': 1, 'i': 'TR 9:30 BO 109', static: true, is_dept: true},
      {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 'CMPS 1063', static: true, is_dept: true},
      {'x': 1, 'y': 3, 'w': 1, 'h': 1, 'i': 'TR 9:30 BO 103', static: true, is_dept: true},
      {'x': 9, 'y': 3, 'w': 1, 'h': 1, 'i': 'MWF 9:00 BO 320', static: true, is_dept: true},
      {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 'CMPS 2084', static: true, is_dept: true},
      {'x': 6, 'y': 4, 'w': 1, 'h': 1, 'i': 'TR 12:30 BO 320', static: true, is_dept: true},
      {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 'CMPS 2143', static: true, is_dept: true},
      {'x': 9, 'y': 5, 'w': 1, 'h': 1, 'i': 'TR 11:00 BO 320', static: true, is_dept: true},
      {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 'CMPS 2433', static: true, is_dept: true},
      {'x': 9, 'y': 6, 'w': 1, 'h': 1, 'i': 'MWF 11:00 BO 209', static: true, is_dept: true},
      {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 'CMPS 3013', static: true, is_dept: true},
      {'x': 1, 'y': 7, 'w': 1, 'h': 1, 'i': 'MWF 9:00 BO 213', static: true, is_dept: true},
      {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 'CMPS 3533', static: true, is_dept: true},
      {'x': 3, 'y': 8, 'w': 1, 'h': 1, 'i': 'MWF 9:00 BO 109', static: true, is_dept: true},
      {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 'CMPS 4103', static: true, is_dept: true},
      {'x': 6, 'y': 9, 'w': 1, 'h': 1, 'i': 'TR 8:00 BO 320', static: true, is_dept: true},
      {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 'CMPS 4123', static: true, is_dept: true},
      {'x': 7, 'y': 10, 'w': 1, 'h': 1, 'i': 'TR 14:00 BO 109', static: true, is_dept: true},
      {'x': 0, 'y': 11, 'w': 1, 'h': 1, 'i': 'CMPS 4143', static: true, is_dept: true},
      {'x': 2, 'y': 11, 'w': 1, 'h': 1, 'i': 'TR 9:30 BO 320', static: true, is_dept: true},
      {'x': 0, 'y': 12, 'w': 1, 'h': 1, 'i': 'CMPS 4453', static: true, is_dept: true},
      {'x': 6, 'y': 12, 'w': 1, 'h': 1, 'i': 'MWF 8:00 BO 320', static: true, is_dept: true},
      {'x': 0, 'y': 13, 'w': 1, 'h': 1, 'i': 'CMPS 4883', static: true, is_dept: true},
      {'x': 2, 'y': 13, 'w': 1, 'h': 1, 'i': 'MW 14:00 BO 103', static: true, is_dept: true},
      {'x': 0, 'y': 14, 'w': 1, 'h': 1, 'i': 'CMPS 5113', static: true, is_dept: true},
      {'x': 1, 'y': 14, 'w': 1, 'h': 1, 'i': 'MW 15:30 BO 209', static: true, is_dept: true},
      {'x': 4, 'y': 14, 'w': 1, 'h': 1, 'i': 'MW 15:30 BO 320', static: true, is_dept: true},
      {'x': 0, 'y': 15, 'w': 1, 'h': 1, 'i': 'CMPS 5133', static: true, is_dept: true},
      {'x': 7, 'y': 15, 'w': 1, 'h': 1, 'i': 'MW 14:00 BO 320', static: true, is_dept: true},
      {'x': 0, 'y': 16, 'w': 1, 'h': 1, 'i': 'CMPS 5143', static: true, is_dept: true},
      {'x': 2, 'y': 16, 'w': 1, 'h': 1, 'i': 'TR 14:00 BO 320', static: true, is_dept: true},
      {'x': 0, 'y': 17, 'w': 1, 'h': 1, 'i': 'CMPS 5363', static: true, is_dept: true},
      {'x': 8, 'y': 17, 'w': 1, 'h': 1, 'i': 'TR 15:30 BO 320', static: true, is_dept: true},
      {'x': 0, 'y': 18, 'w': 1, 'h': 1, 'i': 'CMPS 5443', static: true, is_dept: true},
      {'x': 4, 'y': 18, 'w': 1, 'h': 1, 'i': 'W 11:00 BO 320', static: true, is_dept: true},
    ],
    faculty_MWF: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 'Colmenares - Diaz', 'static': true},
    {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 'Griffin', 'static': true},
    {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 'Hood', 'static': true},
    {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 'Johnson', 'static': true},
    {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 'Morgan', 'static': true},
    {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 'Passos', 'static': true},
    {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 'Roychoudhuri', 'static': true},
    {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 'Smith', 'static': true},
    {'x': 9, 'y': 0, 'w': 1, 'h': 1, 'i': 'Stringfellow', 'static': true},
    {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': '800', 'static': true},
    {'x': 3,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'CMPS 4453 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 6,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'CMPS 4453 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': '900', 'static': true},
    {'x': 1,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'CMPS 1063 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 3,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'CMPS 1063 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 5,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'CMPS 1063 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 9,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'CMPS 1063 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': '1100', 'static': true},
    {'x': 3,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'CMPS 2433 BO 209',
     'static': true,
     'is_dept': true},
    {'x': 4,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'CMPS 2433 BO 209',
     'static': true,
     'is_dept': true},
    {'x': 5,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'CMPS 2433 BO 209',
     'static': true,
     'is_dept': true},
    {'x': 9,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'CMPS 2433 BO 209',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': '1300', 'static': true},
    {'x': 6,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'CMPS 2084 BO 109',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': '1400', 'static': true},
    {'x': 2,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'CMPS 5133 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 7,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'CMPS 5133 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': '1500', 'static': true},
    {'x': 6,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'CMPS 2084 BO 109',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': '1530', 'static': true},
    {'x': 1,
     'y': 7,
     'w': 1,
     'h': 1,
     'i': 'CMPS 5113 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 4,
     'y': 7,
     'w': 1,
     'h': 1,
     'i': 'CMPS 5113 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 8,
     'y': 7,
     'w': 1,
     'h': 1,
     'i': 'CMPS 5113 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': '1700', 'static': true},
    {'x': 2,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'CMPS 5143 BO 320',
     'static': true,
     'is_dept': true}],
    faculty_TR: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 'Colmenares - Diaz', 'static': true},
    {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 'Griffin', 'static': true},
    {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 'Hood', 'static': true},
    {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 'Johnson', 'static': true},
    {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 'Morgan', 'static': true},
    {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 'Passos', 'static': true},
    {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 'Roychoudhuri', 'static': true},
    {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 'Smith', 'static': true},
    {'x': 9, 'y': 0, 'w': 1, 'h': 1, 'i': 'Stringfellow', 'static': true},
    {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': '800', 'static': true},
    {'x': 3,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'CMPS 4103 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 6,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'CMPS 4103 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': '930', 'static': true},
    {'x': 1,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'CMPS 1044 BO 109',
     'static': true,
     'is_dept': true},
    {'x': 2,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'CMPS 1044 BO 109',
     'static': true,
     'is_dept': true},
    {'x': 7,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'CMPS 1044 BO 109',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': '1100', 'static': true},
    {'x': 3,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'CMPS 2143 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 4,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'CMPS 2143 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 5,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'CMPS 2143 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 9,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'CMPS 2143 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': '1230', 'static': true},
    {'x': 6,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'CMPS 2084 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': '1400', 'static': true},
    {'x': 2,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'CMPS 4123 BO 109',
     'static': true,
     'is_dept': true},
    {'x': 7,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'CMPS 4123 BO 109',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': '1530', 'static': true},
    {'x': 1,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'CMPS 5363 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 4,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'CMPS 5363 BO 320',
     'static': true,
     'is_dept': true},
    {'x': 8,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'CMPS 5363 BO 320',
     'static': true,
     'is_dept': true}],
    location_time_MWF: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 100, static: true, is_dept: false},
    {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 101, static: true, is_dept: false},
    {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 103, static: true, is_dept: false},
    {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 105, static: true, is_dept: false},
    {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 109, static: true, is_dept: false},
    {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 115, static: true, is_dept: false},
    {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 117, static: true, is_dept: false},
    {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 125, static: true, is_dept: false},
    {'x': 9, 'y': 0, 'w': 1, 'h': 1, 'i': 127, static: true, is_dept: false},
    {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 800, static: true, is_dept: false},
    {'x': 2,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Hood - MATH 1233',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 1053',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Schmitter - MATH 1634',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 900, static: true, is_dept: false},
    {'x': 2,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'McDonald - MATH 1233',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Hood - CMPS 3533',
     'static': true,
     'is_dept': true},
    {'x': 6,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Mahmud - ENSC 1114',
     'static': true,
     'is_dept': false},
    {'x': 8,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Rosscoe - GEOS 3034',
     'static': true,
     'is_dept': false},
    {'x': 9,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Georges Insalaco - BIOL 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 1000, static: true, is_dept: false},
    {'x': 2,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Schmitter - MATH 1053',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Lopez - MATH 3753',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Meddaugh - GEOS 4533',
     'static': true,
     'is_dept': false},
    {'x': 9,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 1100, static: true, is_dept: false},
    {'x': 1,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Hansen - CHEM 2003',
     'static': true,
     'is_dept': false},
    {'x': 2,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Bernard - MATH 1233',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Morgan - CMPS 1044',
     'static': true,
     'is_dept': true},
    {'x': 5,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Hood - MATH 1634',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Price - GEOS 3134',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Mahmud - ENSC 1114',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 1200, static: true, is_dept: false},
    {'x': 9,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Rosscoe - GEOS 1234',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 1300, static: true, is_dept: false},
    {'x': 2,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 2033',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Passos - CMPS 2084',
     'static': true,
     'is_dept': true},
    {'x': 6,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Meddaugh - GEOS 4533',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 8,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Price - GNSC 1204',
     'static': true,
     'is_dept': false},
    {'x': 9,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Mahmud - ENSC 1114',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 1330, static: true, is_dept: false},
    {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 1400, static: true, is_dept: false},
    {'x': 3,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Griffin - CMPS 4883',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 1500, static: true, is_dept: false},
    {'x': 2,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 1053',
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 5863',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Passos - CMPS 2084',
     'static': true,
     'is_dept': true},
    {'x': 6,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Price - GEOS 3134',
     'static': true,
     'is_dept': false},
    {'x': 8,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Rosscoe - GEOS 5313',
     'static': true,
     'is_dept': false},
    {'x': 9,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Georges Insalaco - BIOL 1013',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 1530, static: true, is_dept: false},
    {'x': 0, 'y': 11, 'w': 1, 'h': 1, 'i': 1600, static: true, is_dept: false},
    {'x': 6,
     'y': 11,
     'w': 1,
     'h': 1,
     'i': 'Price - GEOS 6001',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 12, 'w': 1, 'h': 1, 'i': 1630, static: true, is_dept: false},
    {'x': 4,
     'y': 12,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 5863',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 13, 'w': 1, 'h': 1, 'i': 1700, static: true, is_dept: false},
    {'x': 0, 'y': 14, 'w': 1, 'h': 1, 'i': 1730, static: true, is_dept: false}],
    location_time_TR: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 100, static: true, is_dept: false},
    {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 101, static: true, is_dept: false},
    {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 103, static: true, is_dept: false},
    {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 105, static: true, is_dept: false},
    {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 109, static: true, is_dept: false},
    {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 115, static: true, is_dept: false},
    {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 117, static: true, is_dept: false},
    {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 125, static: true, is_dept: false},
    {'x': 9, 'y': 0, 'w': 1, 'h': 1, 'i': 127, static: true, is_dept: false},
    {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 800, static: true, is_dept: false},
    {'x': 2,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Hood - MATH 233',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 53',
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Mahmud - GEOS 3044',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 900, static: true, is_dept: false},
    {'x': 4,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Mahmud - GEOS 3044',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 930, static: true, is_dept: false},
    {'x': 2,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Schmitter - MATH 53',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Colmenares - Diaz - CMPS 1063',
     'static': true,
     'is_dept': true},
    {'x': 5,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Roychoudhuri - CMPS 1044',
     'static': true,
     'is_dept': true},
    {'x': 9,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Bradley - BIOL 1234',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 1100, static: true, is_dept: false},
    {'x': 1,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Scales - BIOL 1234',
     'static': true,
     'is_dept': false},
    {'x': 2,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 2043',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Johnson - CMPS 1023',
     'static': true,
     'is_dept': true},
    {'x': 5,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Lopez - STAT 3573',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 1230, static: true, is_dept: false},
    {'x': 1,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Shipley - BIOL 4524',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Slavens - MATH 2753',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Schmitter - STAT 3573',
     'static': true,
     'is_dept': false},
    {'x': 9,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Bradley - BIOL 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 1300, static: true, is_dept: false},
    {'x': 6,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 1330, static: true, is_dept: false},
    {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 1400, static: true, is_dept: false},
    {'x': 5,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Roychoudhuri - CMPS 4123',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 1500, static: true, is_dept: false},
    {'x': 6,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Rosscoe - GEOS 1234',
     'static': true,
     'is_dept': false},
    {'x': 8,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Rosscoe - GEOS 3034',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 1530, static: true, is_dept: false},
    {'x': 0, 'y': 11, 'w': 1, 'h': 1, 'i': 1600, static: true, is_dept: false},
    {'x': 0, 'y': 12, 'w': 1, 'h': 1, 'i': 1700, static: true, is_dept: false},
    {'x': 0, 'y': 13, 'w': 1, 'h': 1, 'i': 1730, static: true, is_dept: false}],
    location_time_MWF_2nd: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 203, static: true, is_dept: false},
    {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 205, static: true, is_dept: false},
    {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 209, static: true, is_dept: false},
    {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 213, static: true, is_dept: false},
    {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 214, static: true, is_dept: false},
    {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 215, static: true, is_dept: false},
    {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 217, static: true, is_dept: false},
    {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 223, static: true, is_dept: false},
    {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 800, static: true, is_dept: false},
    {'x': 3,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Pegg - BIOL 3214',
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Masuoka - BIOL 2144',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 900, static: true, is_dept: false},
    {'x': 3,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Scales - BIOL 4714',
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Colmenares - Diaz - CMPS 3013',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 1000, static: true, is_dept: false},
    {'x': 2,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 3',
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Willis - BIOL 3113',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Georges Insalaco - BIOL 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 1100, static: true, is_dept: false},
    {'x': 2,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 3',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Stringfellow - CMPS 2433',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 1200, static: true, is_dept: false},
    {'x': 4,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Bernard - MATH 2534',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 1300, static: true, is_dept: false},
    {'x': 3,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 3',
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'McDonald - MATH 1233',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Bradley - BIOL 1234',
     'static': true,
     'is_dept': false},
    {'x': 8,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Masuoka - BIOL 4021',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 1330, static: true, is_dept: false},
    {'x': 1,
     'y': 7,
     'w': 1,
     'h': 1,
     'i': 'Machunis-Masuoka - BIOL 1214',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 7,
     'w': 1,
     'h': 1,
     'i': 'Pegg - BIOL 1114',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 1400, static: true, is_dept: false},
    {'x': 2,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Scales - BIOL 3334',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Pegg - BIOL 3214',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 1500, static: true, is_dept: false},
    {'x': 7,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Georges Insalaco - BIOL 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 1530, static: true, is_dept: false},
    {'x': 3,
     'y': 10,
     'w': 1,
     'h': 1,
     'i': 'Colmenares - Diaz - CMPS 5113',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 11, 'w': 1, 'h': 1, 'i': 1600, static: true, is_dept: false},
    {'x': 1,
     'y': 11,
     'w': 1,
     'h': 1,
     'i': 'Machunis-Masuoka - BIOL 1214',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 11,
     'w': 1,
     'h': 1,
     'i': 'STAFF - BIOL 1114',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 12, 'w': 1, 'h': 1, 'i': 1630, static: true, is_dept: false},
    {'x': 0, 'y': 13, 'w': 1, 'h': 1, 'i': 1700, static: true, is_dept: false},
    {'x': 7,
     'y': 13,
     'w': 1,
     'h': 1,
     'i': 'STAFF - BIOL 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 14, 'w': 1, 'h': 1, 'i': 1730, static: true, is_dept: false},
    {'x': 3,
     'y': 14,
     'w': 1,
     'h': 1,
     'i': 'Machunis-Masuoka - BIOL 5803',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 14,
     'w': 1,
     'h': 1,
     'i': 'Vogtsberger - BIOL 5002',
     'static': true,
     'is_dept': false}],
    location_time_TR_2nd: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 203, static: true, is_dept: false},
    {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 205, static: true, is_dept: false},
    {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 207, static: true, is_dept: false},
    {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 209, static: true, is_dept: false},
    {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 213, static: true, is_dept: false},
    {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 214, static: true, is_dept: false},
    {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 215, static: true, is_dept: false},
    {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 217, static: true, is_dept: false},
    {'x': 9, 'y': 0, 'w': 1, 'h': 1, 'i': 223, static: true, is_dept: false},
    {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 800, static: true, is_dept: false},
    {'x': 4,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Scales - BIOL 3334',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Willis - BIOL 4333',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 900, static: true, is_dept: false},
    {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 930, static: true, is_dept: false},
    {'x': 4,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Vogtsberger - BIOL 3434',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Shipley - BIOL 3104',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 1100, static: true, is_dept: false},
    {'x': 4,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Masuoka - BIOL 4023',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Pegg - BIOL 1114',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 1230, static: true, is_dept: false},
    {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 1300, static: true, is_dept: false},
    {'x': 2,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Shipley - BIOL 3104',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Vogtsberger - BIOL 3434',
     'static': true,
     'is_dept': false},
    {'x': 8,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Bradley - BIOL 1234',
     'static': true,
     'is_dept': false},
    {'x': 9,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Masuoka - BIOL 2144',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 1330, static: true, is_dept: false},
    {'x': 1,
     'y': 7,
     'w': 1,
     'h': 1,
     'i': 'Machunis-Masuoka - BIOL 1214',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 7,
     'w': 1,
     'h': 1,
     'i': 'Pegg - BIOL 1114',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 1400, static: true, is_dept: false},
    {'x': 1,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Willis - BIOL 4333',
     'static': true,
     'is_dept': false},
    {'x': 2,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Scales - BIOL 3334',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Shipley - BIOL 4524',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Bernard - MATH 3433',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 1500, static: true, is_dept: false},
    {'x': 2,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Shipley - BIOL 3104',
     'static': true,
     'is_dept': false},
    {'x': 8,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Georges Insalaco - BIOL 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 1530, static: true, is_dept: false},
    {'x': 9,
     'y': 10,
     'w': 1,
     'h': 1,
     'i': 'Masuoka - BIOL 2144',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 11, 'w': 1, 'h': 1, 'i': 1600, static: true, is_dept: false},
    {'x': 1,
     'y': 11,
     'w': 1,
     'h': 1,
     'i': 'Machunis-Masuoka - BIOL 1214',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 11,
     'w': 1,
     'h': 1,
     'i': 'Pegg - BIOL 1114',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 12, 'w': 1, 'h': 1, 'i': 1700, static: true, is_dept: false},
    {'x': 8,
     'y': 12,
     'w': 1,
     'h': 1,
     'i': 'STAFF - BIOL 1234',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 13, 'w': 1, 'h': 1, 'i': 1730, static: true, is_dept: false},
    {'x': 7,
     'y': 13,
     'w': 1,
     'h': 1,
     'i': 'Scales - BIOL 5011',
     'static': true,
     'is_dept': false}],
    location_time_MWF_3rd: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 304, static: true, is_dept: false},
    {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 309, static: true, is_dept: false},
    {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 311, static: true, is_dept: false},
    {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 312, static: true, is_dept: false},
    {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 314, static: true, is_dept: false},
    {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 320, static: true, is_dept: false},
    {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 323, static: true, is_dept: false},
    {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 800, static: true, is_dept: false},
    {'x': 1,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Price - GNSC 1204',
     'static': true,
     'is_dept': false},
    {'x': 2,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Mitchell - MATH 1433',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Lopez - MATH 1053',
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Knox - MATH 1734',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Slavens - MATH 1534',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Passos - CMPS 4453',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 900, static: true, is_dept: false},
    {'x': 1,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Liang - CHEM 1143',
     'static': true,
     'is_dept': false},
    {'x': 2,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Bernard - MATH 1233',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': "O'Brien - MATH 1233",
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Mitchell - MATH 1433',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Mescher - MATH 3',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Stringfellow - CMPS 1063',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 1000, static: true, is_dept: false},
    {'x': 1,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Shao - CHEM 3305',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Slavens - MATH 1233',
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Machunis-Masuoka - CHEM 1243',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Knox - MATH 1203',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 1100, static: true, is_dept: false},
    {'x': 2,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Machunis-Masuoka - BIOL 1214',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Johnson - CMPS 5443',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 1200, static: true, is_dept: false},
    {'x': 3,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Slavens - MATH 1233',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 1300, static: true, is_dept: false},
    {'x': 2,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Shao - CHEM 4001',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Jones - MATH 3',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Shao - CHEM 3305',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 1330, static: true, is_dept: false},
    {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 1400, static: true, is_dept: false},
    {'x': 4,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Mescher - MATH 3',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Jones - MATH 1203',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Roychoudhuri - CMPS 5133',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 1500, static: true, is_dept: true},
    {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 1530, static: true, is_dept: false},
    {'x': 6,
     'y': 10,
     'w': 1,
     'h': 1,
     'i': 'Johnson - CMPS 5113',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 11, 'w': 1, 'h': 1, 'i': 1600, static: true, is_dept: false},
    {'x': 0, 'y': 12, 'w': 1, 'h': 1, 'i': 1630, static: true, is_dept: false},
    {'x': 0, 'y': 13, 'w': 1, 'h': 1, 'i': 1700, static: true, is_dept: false},
    {'x': 6,
     'y': 13,
     'w': 1,
     'h': 1,
     'i': 'Griffin - CMPS 5143',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 14, 'w': 1, 'h': 1, 'i': 1730, static: true, is_dept: false}],
    location_time_TR_3rd: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 304, static: true, is_dept: false},
    {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 309, static: true, is_dept: false},
    {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 311, static: true, is_dept: false},
    {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 312, static: true, is_dept: false},
    {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 314, static: true, is_dept: false},
    {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 320, static: true, is_dept: false},
    {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 800, static: true, is_dept: false},
    {'x': 2,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Mitchell - MATH 1233',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Lopez - MATH 53',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Passos - CMPS 4103',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 900, static: true, is_dept: false},
    {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 930, static: true, is_dept: false},
    {'x': 1,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Fulton - CHEM 1143',
     'static': true,
     'is_dept': false},
    {'x': 2,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'McDonald - MATH 3004',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': "O'Brien - MATH 233",
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Liang - CHEM 4243',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Griffin - CMPS 4143',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 1100, static: true, is_dept: false},
    {'x': 1,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Shao - CHEM 3504',
     'static': true,
     'is_dept': false},
    {'x': 2,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Knox - MATH 1053',
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Liang - CHEM 1303',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'McDonald - MATH 1433',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Stringfellow - CMPS 2143',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 1230, static: true, is_dept: false},
    {'x': 5,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Jones - MATH 3',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Passos - CMPS 2084',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 1300, static: true, is_dept: false},
    {'x': 2,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Liang - BIOL 5242',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 1330, static: true, is_dept: false},
    {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 1400, static: true, is_dept: false},
    {'x': 5,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Jones - MATH 203',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Griffin - CMPS 5143',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 1500, static: true, is_dept: false},
    {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 1530, static: true, is_dept: false},
    {'x': 2,
     'y': 10,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 1053',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 10,
     'w': 1,
     'h': 1,
     'i': 'Smith - CMPS 5363',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 11, 'w': 1, 'h': 1, 'i': 1600, static: true, is_dept: false},
    {'x': 0, 'y': 12, 'w': 1, 'h': 1, 'i': 1700, static: true, is_dept: false},
    {'x': 0, 'y': 13, 'w': 1, 'h': 1, 'i': 1730, static: true, is_dept: false}],
    faculty_time_MWF:[],
    faculty_time_TR:[],
  };
}


export default createStore({
  state: loadSavedState(),
  mutations: {
    setUser(state, userData) {
        state.user.email = userData.email;
        state.user.uid = userData.uid;
        state.user.isAuthenticated = true;  // Set isAuthenticated to true when user is set
      },
    clearUser(state) {
        state.user = { email: null, uid: null, isAuthenticated: false };
      },
    updateLayout(state, newLayout){
      state.layout = newLayout;
    },
    updateExample(state, newExample){
      state.example = newExample;
    },
    update_faculty_course(state, new_faculty_course){
      state.faculty_course = new_faculty_course;
    },
    update_faculty_MWF(state, new_faculty_MWF){
      state.faculty_MWF = new_faculty_MWF;
    },
    update_faculty_TR(state, new_faculty_TR){
      state.faculty_TR = new_faculty_TR;
    },
    update_location_time_MWF(state, new_location_time_MWF){
      state.location_time_MWF = new_location_time_MWF;
    },
    update_location_time_TR(state, new_location_time_TR){
      state.location_time_TR = new_location_time_TR;
    },
    update_location_time_MWF_2nd(state, new_location_time_MWF_2nd){
      state.location_time_MWF_2nd = new_location_time_MWF_2nd;
    },
    update_location_time_TR_2nd(state, new_location_time_TR_2nd){
      state.location_time_TR_2nd = new_location_time_TR_2nd;
    },
    update_location_time_MWF_3rd(state, new_location_time_MWF_3rd){
      state.location_time_MWF_3rd = new_location_time_MWF_3rd;
    },
    update_location_time_TR_3rd(state, new_location_time_TR_3rd){
      state.location_time_TR_3rd = new_location_time_TR_3rd;
    },
  },
  getters: {
    isUserAuthenticated: (state) => state.user.isAuthenticated,
    userId: (state) => state.user.uid,
    userEmail: (state) => state.user.email,
    userDepartment: (state) => state.user.department,
    getExample: (state) => state.example,
    get_faculty_course: (state) => state.faculty_course,
    get_faculty_MWF: (state) => state.faculty_MWF,
    get_faculty_TR: (state) => state.faculty_TR,
    get_location_time_MWF: (state) => state.location_time_MWF,
    get_location_time_TR: (state) => state.location_time_TR,
    get_location_time_MWF_2nd: (state) => state.location_time_MWF_2nd,
    get_location_time_TR_2nd: (state) => state.location_time_TR_2nd,
    get_location_time_MWF_3rd: (state) => state.location_time_MWF_3rd,
    get_location_time_TR_3rd: (state) => state.location_time_TR_3rd,
  },
});
