// src/store/index.js
import { createStore } from 'vuex';

export default createStore({
  state: {
    user: {
      email: null,
      uid: null,
      isAuthenticated: false,
      department: "CMPS",
    },
    layout:[],
    example: [
      { x: 2, y: 0, w: 2, h: 1, i: 'W', static: true },
      { x: 4, y: 0, w: 2, h: 1, i: 'E', static: true },
      { x: 6, y: 0, w: 2, h: 1, i: 'L', static: true },
      { x: 8, y: 0, w: 2, h: 1, i: 'C', static: true },
      { x: 10, y: 0, w: 2, h: 1, i: 'O', static: true },
      { x: 12, y: 0, w: 2, h: 1, i: 'M', static: true },
      { x: 14, y: 0, w: 2, h: 1, i: 'E', static: true },
      { x: 0, y: 1, w: 2, h: 2, i: 'M', static: true },
      { x: 0, y: 3, w: 2, h: 2, i: 'S', static: true },
      { x: 0, y: 5, w: 2, h: 2, i: 'U', static: true },
      { x: 0, y: 7, w: 2, h: 2, i: '11am', static: true },
      { x: 0, y: 9, w: 2, h: 2, i: '12am', static: true },
      { x: 0, y: 11, w: 2, h: 2, i: '1pm', static: true },
      { x: 0, y: 13, w: 2, h: 2, i: '2pm', static: true },
      { x: 0, y: 15, w: 2, h: 2, i: '3pm', static: true },
      { x: 0, y: 17, w: 2, h: 2, i: '4pm', static: true },
      { x: 0, y: 19, w: 2, h: 2, i: '5pm', static: true },
      { x: 6, y: 8, w: 2, h: 2, i: 'Class1', static: false },
    ],
    faculty_course: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 'Colmenares - Diaz', 'static': true},
      {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 'Griffin', 'static': true},
      {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 'Hood', 'static': true},
      {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 'Johnson', 'static': true},
      {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 'Morgan', 'static': true},
      {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 'Passos', 'static': true},
      {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 'Roychoudhuri', 'static': true},
      {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 'Smith', 'static': true},
      {'x': 9, 'y': 0, 'w': 1, 'h': 1, 'i': 'Stringfellow', 'static': true},
      {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 'CMPS 1023', 'static': true},
      {'x': 4, 'y': 1, 'w': 1, 'h': 1, 'i': 'TR 11:00 BO 103', 'static': true},
      {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 'CMPS 1044', 'static': true},
      {'x': 5, 'y': 2, 'w': 1, 'h': 1, 'i': 'MWF 9:00 BO 207', 'static': true},
      {'x': 7, 'y': 2, 'w': 1, 'h': 1, 'i': 'TR 9:30 BO 109', 'static': true},
      {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 'CMPS 1063', 'static': true},
      {'x': 1, 'y': 3, 'w': 1, 'h': 1, 'i': 'TR 9:30 BO 103', 'static': true},
      {'x': 9, 'y': 3, 'w': 1, 'h': 1, 'i': 'MWF 9:00 BO 320', 'static': true},
      {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 'CMPS 2084', 'static': true},
      {'x': 6, 'y': 4, 'w': 1, 'h': 1, 'i': 'TR 12:30 BO 320', 'static': true},
      {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 'CMPS 2143', 'static': true},
      {'x': 9, 'y': 5, 'w': 1, 'h': 1, 'i': 'TR 11:00 BO 320', 'static': true},
      {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 'CMPS 2433', 'static': true},
      {'x': 9, 'y': 6, 'w': 1, 'h': 1, 'i': 'MWF 11:00 BO 209', 'static': true},
      {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 'CMPS 3013', 'static': true},
      {'x': 1, 'y': 7, 'w': 1, 'h': 1, 'i': 'MWF 9:00 BO 213', 'static': true},
      {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 'CMPS 3533', 'static': true},
      {'x': 3, 'y': 8, 'w': 1, 'h': 1, 'i': 'MWF 9:00 BO 109', 'static': true},
      {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 'CMPS 4103', 'static': true},
      {'x': 6, 'y': 9, 'w': 1, 'h': 1, 'i': 'TR 8:00 BO 320', 'static': true},
      {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 'CMPS 4123', 'static': true},
      {'x': 7, 'y': 10, 'w': 1, 'h': 1, 'i': 'TR 14:00 BO 109', 'static': true},
      {'x': 0, 'y': 11, 'w': 1, 'h': 1, 'i': 'CMPS 4143', 'static': true},
      {'x': 2, 'y': 11, 'w': 1, 'h': 1, 'i': 'TR 9:30 BO 320', 'static': true},
      {'x': 0, 'y': 12, 'w': 1, 'h': 1, 'i': 'CMPS 4453', 'static': true},
      {'x': 6, 'y': 12, 'w': 1, 'h': 1, 'i': 'MWF 8:00 BO 320', 'static': true},
      {'x': 0, 'y': 13, 'w': 1, 'h': 1, 'i': 'CMPS 4883', 'static': true},
      {'x': 2, 'y': 13, 'w': 1, 'h': 1, 'i': 'MW 14:00 BO 103', 'static': true},
      {'x': 0, 'y': 14, 'w': 1, 'h': 1, 'i': 'CMPS 5113', 'static': true},
      {'x': 1, 'y': 14, 'w': 1, 'h': 1, 'i': 'MW 15:30 BO 209', 'static': true},
      {'x': 4, 'y': 14, 'w': 1, 'h': 1, 'i': 'MW 15:30 BO 320', 'static': true},
      {'x': 0, 'y': 15, 'w': 1, 'h': 1, 'i': 'CMPS 5133', 'static': true},
      {'x': 7, 'y': 15, 'w': 1, 'h': 1, 'i': 'MW 14:00 BO 320', 'static': true},
      {'x': 0, 'y': 16, 'w': 1, 'h': 1, 'i': 'CMPS 5143', 'static': true},
      {'x': 2, 'y': 16, 'w': 1, 'h': 1, 'i': 'TR 14:00 BO 320', 'static': true},
      {'x': 0, 'y': 17, 'w': 1, 'h': 1, 'i': 'CMPS 5363', 'static': true},
      {'x': 8, 'y': 17, 'w': 1, 'h': 1, 'i': 'TR 15:30 BO 320', 'static': true},
      {'x': 0, 'y': 18, 'w': 1, 'h': 1, 'i': 'CMPS 5443', 'static': true},
      {'x': 4, 'y': 18, 'w': 1, 'h': 1, 'i': 'W 11:00 BO 320', 'static': true},
    ],
    faculty_MWF: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 'Colmenares - Diaz', 'static': true},
     {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 'Griffin', 'static': true},
     {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 'Hood', 'static': true},
     {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 'Johnson', 'static': true},
     {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 'Morgan', 'static': true},
     {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 'Passos', 'static': true},
     {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 'Roychoudhuri', 'static': true},
     {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 'Smith', 'static': true},
     {'x': 9, 'y': 0, 'w': 1, 'h': 1, 'i': 'Stringfellow', 'static': true},
     {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 'CMPS 1044', 'static': true},
     {'x': 5, 'y': 1, 'w': 1, 'h': 1, 'i': 'MWF 900 BO 207', 'static': true},
     {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 'CMPS 1063', 'static': true},
     {'x': 9, 'y': 2, 'w': 1, 'h': 1, 'i': 'MWF 900 BO 320', 'static': true},
     {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 'CMPS 2084', 'static': true},
     {'x': 6, 'y': 3, 'w': 1, 'h': 1, 'i': 'W 1300 BO 109', 'static': true},
     {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 'CMPS 2433', 'static': true},
     {'x': 9, 'y': 4, 'w': 1, 'h': 1, 'i': 'MWF 1100 BO 209', 'static': true},
     {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 'CMPS 3013', 'static': true},
     {'x': 1, 'y': 5, 'w': 1, 'h': 1, 'i': 'MWF 900 BO 213', 'static': true},
     {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 'CMPS 3533', 'static': true},
     {'x': 3, 'y': 6, 'w': 1, 'h': 1, 'i': 'MWF 900 BO 109', 'static': true},
     {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 'CMPS 4453', 'static': true},
     {'x': 6, 'y': 7, 'w': 1, 'h': 1, 'i': 'MWF 800 BO 320', 'static': true},
     {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 'CMPS 4883', 'static': true},
     {'x': 2, 'y': 8, 'w': 1, 'h': 1, 'i': 'MW 1400 BO 103', 'static': true},
     {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 'CMPS 5113', 'static': true},
     {'x': 1, 'y': 9, 'w': 1, 'h': 1, 'i': 'MW 1530 BO 209', 'static': true},
     {'x': 4, 'y': 9, 'w': 1, 'h': 1, 'i': 'MW 1530 BO 320', 'static': true},
     {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 'CMPS 5133', 'static': true},
     {'x': 7, 'y': 10, 'w': 1, 'h': 1, 'i': 'MW 1400 BO 320', 'static': true},
     {'x': 0, 'y': 11, 'w': 1, 'h': 1, 'i': 'CMPS 5143', 'static': true},
     {'x': 2, 'y': 11, 'w': 1, 'h': 1, 'i': 'MW 1700 BO 320', 'static': true},
     {'x': 0, 'y': 12, 'w': 1, 'h': 1, 'i': 'CMPS 5443', 'static': true},
     {'x': 4, 'y': 12, 'w': 1, 'h': 1, 'i': 'W 1100 BO 320', 'static': true},
    ],
    faculty_TR: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 'Colmenares - Diaz', 'static': true},
    {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 'Griffin', 'static': true},
    {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 'Hood', 'static': true},
    {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 'Johnson', 'static': true},
    {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 'Morgan', 'static': true},
    {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 'Passos', 'static': true},
    {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 'Roychoudhuri', 'static': true},
    {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 'Smith', 'static': true},
    {'x': 9, 'y': 0, 'w': 1, 'h': 1, 'i': 'Stringfellow', 'static': true},
    {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 'CMPS 1023', 'static': true},
    {'x': 4, 'y': 1, 'w': 1, 'h': 1, 'i': 'TR 1100 BO 103', 'static': true},
    {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 'CMPS 1044', 'static': true},
    {'x': 7, 'y': 2, 'w': 1, 'h': 1, 'i': 'TR 930 BO 109', 'static': true},
    {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 'CMPS 1063', 'static': true},
    {'x': 1, 'y': 3, 'w': 1, 'h': 1, 'i': 'TR 930 BO 103', 'static': true},
    {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 'CMPS 2084', 'static': true},
    {'x': 6, 'y': 4, 'w': 1, 'h': 1, 'i': 'TR 1230 BO 320', 'static': true},
    {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 'CMPS 2143', 'static': true},
    {'x': 9, 'y': 5, 'w': 1, 'h': 1, 'i': 'TR 1100 BO 320', 'static': true},
    {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 'CMPS 4103', 'static': true},
    {'x': 6, 'y': 6, 'w': 1, 'h': 1, 'i': 'TR 800 BO 320', 'static': true},
    {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 'CMPS 4123', 'static': true},
    {'x': 7, 'y': 7, 'w': 1, 'h': 1, 'i': 'TR 1400 BO 109', 'static': true},
    {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 'CMPS 4143', 'static': true},
    {'x': 2, 'y': 8, 'w': 1, 'h': 1, 'i': 'TR 930 BO 320', 'static': true},
    {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 'CMPS 5143', 'static': true},
    {'x': 2, 'y': 9, 'w': 1, 'h': 1, 'i': 'TR 1400 BO 320', 'static': true},
    {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 'CMPS 5363', 'static': true},
    {'x': 8, 'y': 10, 'w': 1, 'h': 1, 'i': 'TR 1530 BO 320', 'static': true},
    ],
    location_time_MWF: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 100, 'static': true},
    {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 101, 'static': true},
    {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 103, 'static': true},
    {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 105, 'static': true},
    {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 109, 'static': true},
    {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 115, 'static': true},
    {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 117, 'static': true},
    {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 125, 'static': true},
    {'x': 9, 'y': 0, 'w': 1, 'h': 1, 'i': 127, 'static': true},
    {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 800, 'static': true},
    {'x': 2,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Hood - MATH 1233',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 1053',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Schmitter - MATH 1634',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 900, 'static': true},
    {'x': 2,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'McDonald - MATH 1233',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Hood - CMPS 3533',
     'static': true,
     'is_dept': true},
    {'x': 6,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Mahmud - ENSC 1114',
     'static': true,
     'is_dept': false},
    {'x': 8,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Rosscoe - GEOS 3034',
     'static': true,
     'is_dept': false},
    {'x': 9,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Georges Insalaco - BIOL 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 1000, 'static': true},
    {'x': 2,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Schmitter - MATH 1053',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Lopez - MATH 3753',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Meddaugh - GEOS 4533',
     'static': true,
     'is_dept': false},
    {'x': 9,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 1100, 'static': true},
    {'x': 1,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Hansen - CHEM 2003',
     'static': true,
     'is_dept': false},
    {'x': 2,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Bernard - MATH 1233',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Morgan - CMPS 1044',
     'static': true,
     'is_dept': true},
    {'x': 5,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Hood - MATH 1634',
     'static': true,
     'is_dept': false},
    {'x': 6,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Price - GEOS 3134',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Mahmud - ENSC 1114',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 1200, 'static': true},
    {'x': 9,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Rosscoe - GEOS 1234',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 1300, 'static': true},
    {'x': 2,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 2033',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Passos - CMPS 2084',
     'static': true,
     'is_dept': true},
    {'x': 6,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Meddaugh - GEOS 4533',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 8,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Price - GNSC 1204',
     'static': true,
     'is_dept': false},
    {'x': 9,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Mahmud - ENSC 1114',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 1330, 'static': true},
    {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 1400, 'static': true},
    {'x': 3,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Griffin - CMPS 4883',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 1500, 'static': true},
    {'x': 2,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 1053',
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 5863',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Passos - CMPS 2084',
     'static': true,
     'is_dept': true},
    {'x': 6,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Price - GEOS 3134',
     'static': true,
     'is_dept': false},
    {'x': 8,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Rosscoe - GEOS 5313',
     'static': true,
     'is_dept': false},
    {'x': 9,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Georges Insalaco - BIOL 1013',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 1530, 'static': true},
    {'x': 0, 'y': 11, 'w': 1, 'h': 1, 'i': 1600, 'static': true},
    {'x': 6,
     'y': 11,
     'w': 1,
     'h': 1,
     'i': 'Price - GEOS 6001',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 12, 'w': 1, 'h': 1, 'i': 1630, 'static': true},
    {'x': 4,
     'y': 12,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 5863',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 13, 'w': 1, 'h': 1, 'i': 1700, 'static': true},
    {'x': 0, 'y': 14, 'w': 1, 'h': 1, 'i': 1730, 'static': true}],
    location_time_TR: [{'x': 1, 'y': 0, 'w': 1, 'h': 1, 'i': 100, 'static': true},
    {'x': 2, 'y': 0, 'w': 1, 'h': 1, 'i': 101, 'static': true},
    {'x': 3, 'y': 0, 'w': 1, 'h': 1, 'i': 103, 'static': true},
    {'x': 4, 'y': 0, 'w': 1, 'h': 1, 'i': 105, 'static': true},
    {'x': 5, 'y': 0, 'w': 1, 'h': 1, 'i': 109, 'static': true},
    {'x': 6, 'y': 0, 'w': 1, 'h': 1, 'i': 115, 'static': true},
    {'x': 7, 'y': 0, 'w': 1, 'h': 1, 'i': 117, 'static': true},
    {'x': 8, 'y': 0, 'w': 1, 'h': 1, 'i': 125, 'static': true},
    {'x': 9, 'y': 0, 'w': 1, 'h': 1, 'i': 127, 'static': true},
    {'x': 0, 'y': 1, 'w': 1, 'h': 1, 'i': 800, 'static': true},
    {'x': 2,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Hood - MATH 233',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 53',
     'static': true,
     'is_dept': false},
    {'x': 4,
     'y': 1,
     'w': 1,
     'h': 1,
     'i': 'Mahmud - GEOS 3044',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 2, 'w': 1, 'h': 1, 'i': 900, 'static': true},
    {'x': 4,
     'y': 2,
     'w': 1,
     'h': 1,
     'i': 'Mahmud - GEOS 3044',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 3, 'w': 1, 'h': 1, 'i': 930, 'static': true},
    {'x': 2,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Schmitter - MATH 53',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Colmenares - Diaz - CMPS 1063',
     'static': true,
     'is_dept': true},
    {'x': 5,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Roychoudhuri - CMPS 1044',
     'static': true,
     'is_dept': true},
    {'x': 9,
     'y': 3,
     'w': 1,
     'h': 1,
     'i': 'Bradley - BIOL 1234',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 4, 'w': 1, 'h': 1, 'i': 1100, 'static': true},
    {'x': 1,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Scales - BIOL 1234',
     'static': true,
     'is_dept': false},
    {'x': 2,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Fosnaugh - MATH 2043',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Johnson - CMPS 1023',
     'static': true,
     'is_dept': true},
    {'x': 5,
     'y': 4,
     'w': 1,
     'h': 1,
     'i': 'Lopez - STAT 3573',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 5, 'w': 1, 'h': 1, 'i': 1230, 'static': true},
    {'x': 1,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Shipley - BIOL 4524',
     'static': true,
     'is_dept': false},
    {'x': 3,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Slavens - MATH 2753',
     'static': true,
     'is_dept': false},
    {'x': 5,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Schmitter - STAT 3573',
     'static': true,
     'is_dept': false},
    {'x': 9,
     'y': 5,
     'w': 1,
     'h': 1,
     'i': 'Bradley - BIOL 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 6, 'w': 1, 'h': 1, 'i': 1300, 'static': true},
    {'x': 6,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 6,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 7, 'w': 1, 'h': 1, 'i': 1330, 'static': true},
    {'x': 0, 'y': 8, 'w': 1, 'h': 1, 'i': 1400, 'static': true},
    {'x': 5,
     'y': 8,
     'w': 1,
     'h': 1,
     'i': 'Roychoudhuri - CMPS 4123',
     'static': true,
     'is_dept': true},
    {'x': 0, 'y': 9, 'w': 1, 'h': 1, 'i': 1500, 'static': true},
    {'x': 6,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Katumwehe - GEOS 1134',
     'static': true,
     'is_dept': false},
    {'x': 7,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Rosscoe - GEOS 1234',
     'static': true,
     'is_dept': false},
    {'x': 8,
     'y': 9,
     'w': 1,
     'h': 1,
     'i': 'Rosscoe - GEOS 3034',
     'static': true,
     'is_dept': false},
    {'x': 0, 'y': 10, 'w': 1, 'h': 1, 'i': 1530, 'static': true},
    {'x': 0, 'y': 11, 'w': 1, 'h': 1, 'i': 1600, 'static': true},
    {'x': 0, 'y': 12, 'w': 1, 'h': 1, 'i': 1700, 'static': true},
    {'x': 0, 'y': 13, 'w': 1, 'h': 1, 'i': 1730, 'static': true}],
  },
  mutations: {
    setUser(state, userData) {
        state.user.email = userData.email;
        state.user.uid = userData.uid;
        state.user.isAuthenticated = true;  // Set isAuthenticated to true when user is set
      },
    clearUser(state) {
        state.user = { email: null, uid: null, isAuthenticated: false };
      },
    updateLayout(state, newLayout){
      state.layout = newLayout;
    },
    updateExample(state, newExample){
      state.example = newExample;
    },
    update_faculty_course(state, new_faculty_course){
      state.faculty_course = new_faculty_course;
    },
    update_faculty_MWF(state, new_faculty_MWF){
      state.faculty_MWF = new_faculty_MWF;
    },
    update_faculty_TR(state, new_faculty_TR){
      state.faculty_TR = new_faculty_TR;
    },
    update_location_time_MWF(state, new_location_time_MWF){
      state.location_time_MWF = new_location_time_MWF;
    },
    update_location_time_TR(state, new_location_time_TR){
      state.location_time_TR = new_location_time_TR;
    },
  },
  getters: {
    isUserAuthenticated: (state) => state.user.isAuthenticated,
    userId: (state) => state.user.uid,
    userEmail: (state) => state.user.email,
    userDepartment: (state) => state.user.department,
    getExample: (state) => state.example,
    get_faculty_course: (state) => state.faculty_course,
    get_faculty_MWF: (state) => state.faculty_MWF,
    get_faculty_TR: (state) => state.faculty_TR,
    get_location_time_MWF: (state) => state.location_time_MWF,
    get_location_time_TR: (state) => state.location_time_TR,
  },
});
