# Generated by Django 5.0.3 on 2024-03-28 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="AxisModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("static", models.BooleanField(default=True)),
                ("moved", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.departmentmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("static", models.BooleanField(default=False)),
                ("moved", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.departmentmodel",
                    ),
                ),
            ],
        ),
    ]
